name: Deploy documentation

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node_modules
        run: yarn
      - name: publish to github pages
        run: ./deploy_docs.sh
